# -*- encoding: utf-8 -*-
#
=begin
#imageapi

#Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "cloudmersive-image-recognition-api-client/version"

Gem::Specification.new do |s|
  s.name        = "cloudmersive-image-recognition-api-client"
  s.version     = CloudmersiveImageRecognitionApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Cloudmersive"]
  s.email       = [""]
  s.homepage    = "https://www.cloudmersive.com/image-recognition-and-processing-api"
  s.summary     = "Advanced Machine Learning APIs for recognizing and processing images."
  s.description = "Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, including automatic caption generation, face recognition and NSFW classification, and also perform useful image modification operations."
  s.license     = "Apache 2.0"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = Dir['./**/*']
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
