=begin
#imageapi

#Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveImageRecognitionApiClient::ImageSimilarityHashDistanceRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImageSimilarityHashDistanceRequest' do
  before do
    # run before each test
    @instance = CloudmersiveImageRecognitionApiClient::ImageSimilarityHashDistanceRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImageSimilarityHashDistanceRequest' do
    it 'should create an instance of ImageSimilarityHashDistanceRequest' do
      expect(@instance).to be_instance_of(CloudmersiveImageRecognitionApiClient::ImageSimilarityHashDistanceRequest)
    end
  end
  describe 'test attribute "image_hash1"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "image_hash2"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
