=begin
#imageapi

#Image Recognition and Processing APIs let you use Artificial Intelligence and Machine Learning to recognize and process images, and also perform useful image modification operations.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveImageRecognitionApiClient::AiImageDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AiImageDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersiveImageRecognitionApiClient::AiImageDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AiImageDetectionApi' do
    it 'should create an instance of AiImageDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersiveImageRecognitionApiClient::AiImageDetectionApi)
    end
  end

  # unit tests for ai_image_detection_detect_file
  # Detect if an input image was generated using AI
  # Detects if the input image was generated using AI tools.
  # @param image_file Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
  # @param [Hash] opts the optional parameters
  # @return [ImageAiDetectionResult]
  describe 'ai_image_detection_detect_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
