=begin
#imageapi

#Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveImageRecognitionApiClient::NsfwApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NsfwApi' do
  before do
    # run before each test
    @instance = CloudmersiveImageRecognitionApiClient::NsfwApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NsfwApi' do
    it 'should create an instance of NsfwApi' do
      expect(@instance).to be_instance_of(CloudmersiveImageRecognitionApiClient::NsfwApi)
    end
  end

  # unit tests for nsfw_classify
  # Not safe for work (NSFW) racy content classification
  # Classify an image into Not Safe For Work (NSFW)/Porn/Racy content and Safe Content.
  # @param image_file Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported.
  # @param [Hash] opts the optional parameters
  # @return [NsfwResult]
  describe 'nsfw_classify test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
