=begin
#imageapi

#Image Recognition and Processing APIs let you use Machine Learning to recognize and process images, and also perform useful image modification operations.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveImageRecognitionApiClient::TextGenerationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TextGenerationApi' do
  before do
    # run before each test
    @instance = CloudmersiveImageRecognitionApiClient::TextGenerationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TextGenerationApi' do
    it 'should create an instance of TextGenerationApi' do
      expect(@instance).to be_instance_of(CloudmersiveImageRecognitionApiClient::TextGenerationApi)
    end
  end

  # unit tests for text_generation_create_handwriting_png
  # Create an image of handwriting in PNG format
  # Uses Deep Learning to generate realistic handwriting and returns the result as a PNG image
  # @param request Draw text parameters
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'text_generation_create_handwriting_png test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
